# basic options
title: The Azuy Guy
author: Felipe Nascimento
email: felipe@theazureguy.com
description: Azure from the Inside Out
twitter_username: felipefn88
github_username:  fedonasc

# Build settings
markdown: kramdown
theme: minima
